import { TheoryArticle } from "@/lib/content-models";

const accessedAt = "2026-08-25";

export const THEORY_LIBRARY: TheoryArticle[] = [
  {
    id: "teoria-direitos-fundamentais", areaId: "constitucional-geral", subjectId: "constitucional", topic: "Direitos fundamentais", title: "Direitos fundamentais: leitura tática do art. 5º", tacticalFocus: "Diferenciar garantias, vedações e hipóteses expressas de relativização.", readingMinutes: 6, reviewStatus: "oficial", summary: "O art. 5º reúne direitos e garantias que a banca costuma cobrar pela literalidade. Leia cada inciso identificando o titular do direito, a regra e as exceções expressas.", sections: [{ heading: "Como ler a lei seca", body: "Em questões objetivas, evite transformar uma garantia em regra absoluta sem verificar ressalvas do próprio texto constitucional. Separe direitos individuais, garantias processuais e limites expressos." }, { heading: "Rota de revisão", body: "Depois da leitura, compare pares que geram confusão: inviolabilidade do domicílio, sigilo das comunicações, prisão e devido processo legal." }], keyTakeaways: ["A literalidade da norma é ponto de partida.", "Exceções dependem do texto e do contexto previsto.", "Revise comparando conceitos próximos."], references: [{ title: "Constituição da República Federativa do Brasil — art. 5º", url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm", sourceTier: "primaria", accessedAt }], updatedAt: accessedAt,
  },
  {
    id: "teoria-conectivos", areaId: "logico", subjectId: "portugues", topic: "Conectivos", title: "Conectivos: a relação de sentido que decide a questão", tacticalFocus: "Reconhecer oposição, causa, consequência, condição e conclusão antes de trocar uma expressão.", readingMinutes: 5, reviewStatus: "revisado_editorialmente", summary: "Conectivos não são sinônimos automáticos: eles organizam relações lógicas entre partes do texto. A substituição só é válida se preservar a relação de sentido e a correção gramatical.", sections: [{ heading: "Método em três passos", body: "Localize as duas ideias ligadas pela expressão. Nomeie a relação entre elas. Só então teste uma possível substituição." }, { heading: "Pegadinha frequente", body: "Expressões de oposição, conclusão e explicação podem parecer próximas em frases isoladas, mas alteram a lógica quando inseridas no período." }], keyTakeaways: ["Identifique a relação antes da palavra.", "Substituição exige equivalência de sentido.", "Leia o período completo."], references: [{ title: "Portal de Língua Portuguesa — Governo Federal", url: "https://www.gov.br/mec/pt-br", sourceTier: "institucional", accessedAt }], updatedAt: accessedAt,
  },
  {
    id: "teoria-fracoes", areaId: "matematica-basica", subjectId: "matematica", topic: "Frações", title: "Frações e proporcionalidade: transforme antes de calcular", tacticalFocus: "Usar equivalência, MMC e comparação de grandezas com segurança.", readingMinutes: 6, reviewStatus: "revisado_editorialmente", summary: "Frações representam partes de uma unidade ou razões entre grandezas. Em concurso, o caminho mais seguro é organizar denominadores, simplificar quando possível e conferir se o resultado faz sentido no problema.", sections: [{ heading: "Equivalência", body: "Multiplicar ou dividir numerador e denominador pelo mesmo número não altera o valor da fração." }, { heading: "Soma e subtração", body: "Antes de somar ou subtrair, encontre denominadores compatíveis; o MMC costuma organizar o cálculo." }], keyTakeaways: ["Frações equivalentes preservam o valor.", "MMC serve para igualar denominadores.", "Estime o resultado para verificar o cálculo."], references: [{ title: "Base Nacional Comum Curricular — Matemática", url: "https://www.gov.br/mec/pt-br/assuntos/educacao-basica/bncc", sourceTier: "institucional", accessedAt }], updatedAt: accessedAt,
  },
  {
    id: "teoria-excel", areaId: "informatica", subjectId: "informatica", topic: "Excel", title: "Planilhas: fórmulas essenciais para prova", tacticalFocus: "Distinguir referência de célula, função e resultado esperado em SOMA, MÉDIA e SE.", readingMinutes: 5, reviewStatus: "oficial", summary: "Em planilhas, uma fórmula começa com sinal de igualdade e opera dados de células. A questão normalmente avalia o efeito da função e não a decoração da planilha.", sections: [{ heading: "Funções básicas", body: "SOMA reúne valores, MÉDIA calcula a média aritmética e SE devolve um resultado conforme uma condição lógica." }, { heading: "Leitura de fórmula", body: "Localize os argumentos entre parênteses e verifique se referências relativas ou absolutas seriam alteradas ao copiar a fórmula." }], keyTakeaways: ["Fórmulas começam com =.", "Funções usam argumentos entre parênteses.", "Entenda o resultado antes de decorar sintaxe."], references: [{ title: "Documentação do Excel — Microsoft Learn", url: "https://learn.microsoft.com/pt-br/office/excel/", sourceTier: "institucional", accessedAt }], updatedAt: accessedAt,
  },
  {
    id: "teoria-seguranca-digital", areaId: "informatica", subjectId: "informatica", topic: "Segurança da informação", title: "Segurança digital: identifique o vetor de risco", tacticalFocus: "Diferenciar phishing, engenharia social, malware e boas práticas de proteção.", readingMinutes: 5, reviewStatus: "oficial", summary: "Segurança digital envolve comportamento, dispositivos e dados. Em questões, diferencie o golpe que manipula pessoas do código malicioso que afeta sistemas.", sections: [{ heading: "Phishing e engenharia social", body: "Phishing é uma tentativa de induzir a entrega de dados ou o acesso a conteúdo malicioso. A engenharia social explora confiança, urgência ou medo para manipular decisões." }, { heading: "Proteção", body: "Atualizações, senhas fortes, autenticação adicional e verificação de links reduzem exposição, mas a resposta correta depende do cenário apresentado." }], keyTakeaways: ["Desconfie de urgência e pedidos de dados.", "Verifique remetente e endereço antes de clicar.", "Backup e atualização reduzem impacto."], references: [{ title: "Cartilha de Segurança para Internet — CERT.br", url: "https://cartilha.cert.br/", sourceTier: "institucional", accessedAt }], updatedAt: accessedAt,
  },
];

export function findTheoryForTopic(subjectId: string, topic: string) {
  return THEORY_LIBRARY.find((article) => article.subjectId === subjectId && article.topic.toLocaleLowerCase() === topic.toLocaleLowerCase());
}
